name: Frontend tests with coverage test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Npm install dependencies
        run: npm ci

      - name: Run project tests
        run: npm run test:ci

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: karma-report
          path: front/coverage

      - name: Update coverage badge
        uses:  demyanets/angular-coverage-badges-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage-summary-path: ./front/coverage/bobapp/coverage-summary.json
          badges-directory: ./front/.badges
          protected-branches: '["main"]'

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./front/coverage/bobapp/coverage-cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: ./front/code-coverage-results.md
          header: |
            chore: update code coverage results ${{ github.sha }}
