name: SonarQube on Frontend

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build, analyze and report to SonarCloud
    defaults:
      run:
        working-directory: front

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Npm install dependencies
        run: npm ci

      - name: Build and analyse
        uses: SonarSource/sonarqube-scan-action@v5.1.0
        with:
          projectBaseDir: front
          args: >
            -Dsonar.java.coverage.reportPaths=coverage.xml
            -Dsonar.sources=coverage/bobapp/coverage-lcovonly.txt
            -Dsonar.typescript.tsconfigPaths=tsconfig.json
            -Dsonar.verbose=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}